### ISSUE TITLE
Use official API instead of unofficial one

### ISSUE THREAD

**Issue by JeroenoBoy** [zNotChill/cubed-api#1]
I noticed that you use the api `https://api.znotchill.me/api/cubed` instead of `https://api.playerservers.com/` The zNotChill api is basically the same, except that it reformats the request a bit. It is highly recommended to use the official API or allow users to select their own api.

**Comment by zNotChill** [comment]
Never saw this issue - good idea, I may implement this

**Comment by zNotChill** [comment]
Done
```js
new CubedCraft(CustomAPI.CubedCraft);
new CubedCraft(CustomAPI.zNotChill);

new CubedCraft({
  baseURI: "",
  "userEndpoint": ""
});
```
